[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["@tailwindcss/cli", "-i styles/input.css", "-o styles/tailwind-output.css"]

[hooks.windows]
stage = "pre_build"
command = "cmd"
command_arguments = ["/c npm install -y && npx @tailwindcss/cli -i styles/input.css -o styles/tailwind-output.css"]